wandb_version: 1
undersample:
  value: True
tokenizer:
  value: 'en_core_web_md'
vectors:
  value: 'en_core_web_md'
dataset:
  value: 'babi'
model:
  value: 'universal_transformer'
optimizer:
  value: 'adam'
epochs:
  value: 20
batch_size:
  value: 8
lr:
  value: 0.0001
log:
  value: null
learning_rate_decay_schedule:
  value: null
log_freq:
  value: null
checkpoint_metric:
  value: 'loss'
dataset.debug:
  value: True
model.halting_threshold:
  value: null
model.transition_type:
  value: "depth_wise_conv"
